# Generated by Django 4.1.3 on 2023-12-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0011_alter_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
