# Generated by Django 4.1.3 on 2024-01-18 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_user_friends_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(default=None, help_text='friendlist of the user', to=settings.AUTH_USER_MODEL),
        ),
    ]
